version: 1
disable_existing_loggers: False

formatters:
  json:
    (): pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(name)s %(message)s %(service)s %(request_id)s'

filters:
  add_service_context:
    (): app.config.logger.logger.ServiceFilter

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
    filters: [add_service_context]
    stream: ext://sys.stdout

  # File handler writes to a filename which will be adjusted by setup_logger()
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: json
    filters: [add_service_context]
    filename: app.log

root:
  level: INFO
  handlers: [console, file]

loggers:
  uvicorn.error:
    level: WARNING
    handlers: [console]
    propagate: False

  uvicorn.access:
    level: WARNING
    handlers: [console]
    propagate: False