# Days mapping configuration for travel itinerary processing
# Maps written numbers and patterns to numerical values for duration parsing

default_duration: "3 days"

patterns:
  day_pattern: "(\\d+)\\s*-?\\s*days?"
  week_pattern: "(\\d+)\\s*weeks?"

written_numbers:
  one: 1
  two: 2
  three: 3
  four: 4
  five: 5
  six: 6
  seven: 7
  eight: 8
  nine: 9
  ten: 10
  eleven: 11
  twelve: 12
  thirteen: 13
  fourteen: 14
  fifteen: 15

written_weeks:
  "one week": 7
  "two weeks": 14
  "three weeks": 21
  "four weeks": 28
