app:
  name: voyager-t800
  env: dev
  version: 0.1.0

model:
  openai:
    api_key: ${OPENAI_API_KEY:""}
    model_name: text-embedding-3-small
    temperature: 0.7
    base_url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
  groq:
    api_key: ${GROQ_API_KEY:""}
    model_name: llama3-8b-8192
    temperature: 0.7

embedding:
  provider: openai
  model: text-embedding-3-small
  input_dir: data/raw
  output_dir: data/embeddings
  metadata_csv_path: data/metadata.csv
  max_tokens: 450
  overlap_ratio: 0.2
  batch_size: 64
  polite_delay: 0.1
  retry_attempts: 5
  retry_min_wait: 1.0
  retry_max_wait: 30.0
  chunking_method: sliding
  cleaning_version: v1.2
  supported_extensions:
    - .txt
    - .json

vectordb:
  provider: chroma
  chroma:
    persist_directory: .chroma
    collection: voyager
  weaviate:
    url: ${WEAVIATE_URL:http://localhost:8080}
    api_key: ${WEAVIATE_API_KEY:""}
    class_name: voyager

summary_memory:
  summary_trigger_count: 2
  max_token_limit: 1000

prompt:
  itinerary_template_path: app/prompts/test_itinerary_prompt.txt
  summary_template_path: app/prompts/test_summary_prompt.txt

weather:
  api_key: ${OPENWEATHER_API_KEY:""}
  base_url: ${OPENWEATHER_BASE_URL:https://api.openweathermap.org}
  units: metric
  request_timeout_seconds: 15.0
  cache_ttl_seconds: 3600
  retry_attempts: 3
  retry_backoff_min: 0.5
  retry_backoff_max: 4.0

bedrock:
  enabled: ${BEDROCK_ENABLED:false}
  region_name: ${AWS_REGION:""}
  profile_name: ${AWS_PROFILE:""}
  aws_access_key_id: ${AWS_ACCESS_KEY_ID:""}
  aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY:""}
  aws_session_token: ${AWS_SESSION_TOKEN:""}
  endpoint_url: ${BEDROCK_ENDPOINT_URL:""}
  model_id: ${BEDROCK_MODEL_ID:""}
  temperature: ${BEDROCK_TEMPERATURE:0.7}
  max_tokens: ${BEDROCK_MAX_TOKENS:1024}
  top_p: ${BEDROCK_TOP_P:0.7}
  top_k: ${BEDROCK_TOP_K:5}

attraction_parser:
  csv_file: data/attractions_names_list.csv
  debug_mode: false
  output_dir: data/raw
  metadata_file: data/metadata.csv
  remove_non_latin: true
  preserve_mixed_words: true
  aggressive_filtering: false
  use_see_also: false
  wikipedia_api_url: https://en.wikipedia.org/w/api.php
  user_agent: VoyagerT800AttractionsBot/1.0 (https://example.com/contact)
  rate_limit_delay: 0.5
  summary_max_length: 200

itinerary:
  api_key: ${MAP_API_KEY:""}

tavily:
  tavily_api_key: ${TAVILY_API_KEY:""}
  tavily_api_url: https://api.tavily.com/search
  tavily_max_results: 5
  tavily_country: ukraine
  tavily_include_answer: advanced
  tavily_timeout: 30

logging_config_file: app/config/logger/logger.yaml


